create or replace
PROCEDURE A_PONER_VALOR_FACTURA (MONTO IN NUMBER, vIDFACTURA IN NUMBER) AS 
BEGIN
    UPDATE tabla_facturas.FACTURAS
    SET montototal=(montototal+MONTO)
    WHERE IDFACTURA=vIDFACTURA;
    COMMIT;
END A_PONER_VALOR_FACTURA;