create or replace
PROCEDURE A_RETORNAR_COSTO_HABITACION (vIDHABITACION IN NUMBER, vCOSTOHABITACION out number)AS 
BEGIN
  SELECT COSTOPERSONADIA INTO vCOSTOHABITACION
  FROM TABLA_HOTELES.TIPOHABITACION TB
  WHERE TB.IDTIPOHABITACION IN (SELECT H.IDTIPOHABITACION
                                FROM TABLA_HOTELES.HABITACIONES H
                                WHERE H.IDHABITACION = vIDHABITACION);
END A_RETORNAR_COSTO_HABITACION;