create or replace
FUNCTION A_RETORNAR_NUMERO_DIAS (vIDRESERVA IN NUMBER) RETURN NUMBER AS 
vNUMERO_DIAS NUMBER;
FECHA_FINAL DATE;
FECHA_INICIAL DATE;

BEGIN
  vNUMERO_DIAS :=0;
  
  SELECT R.FECHAFINAL INTO FECHA_FINAL
  FROM TABLA_RESERVAS.RESERVAS R
  WHERE R.IDRESERVA = vIDRESERVA;
  
  SELECT R.FECHAINICIO INTO FECHA_INICIAL
  FROM TABLA_RESERVAS.RESERVAS R
  WHERE R.IDRESERVA = vIDRESERVA;
  
  vNUMERO_DIAS:=FECHA_FINAL- FECHA_INICIAL;
  RETURN vNUMERO_DIAS;
  
END A_RETORNAR_NUMERO_DIAS;