create or replace
PROCEDURE A_RETORNAR_PERSONAS_HABITACION(vIDHABITACION IN NUMBER , NUMERO_PERSONAS out number) AS 
BEGIN
  SELECT H.CANTIDADPERSONAS INTO NUMERO_PERSONAS
  FROM TABLA_HOTELES.HABITACIONES H
  WHERE H.IDHABITACION = vIDHABITACION;
  
END A_RETORNAR_PERSONAS_HABITACION;