create or replace
FUNCTION A_RETORNAR_COSTO_SERVICIO (vIDSERVICIO IN NUMBER) RETURN NUMBER AS 
vCOSTOSERVICIO NUMBER;
BEGIN
  vCOSTOSERVICIO:=0;
  SELECT PRECIOUNITARIO INTO vCOSTOSERVICIO
  FROM TABLA_HOTELES.SERVICIOS SVC
  WHERE SVC.IDSERVICIO=vIDSERVICIO;
  
  RETURN vCOSTOSERVICIO;
END A_RETORNAR_COSTO_SERVICIO;