create or replace
PROCEDURE A_TX2_RETORNAR_COSTOH (vIDHABITACION IN NUMBER, vCOSTOHABITACION out number)AS 
BEGIN
  SELECT COSTOPERSONADIA INTO vCOSTOHABITACION
  FROM TABLA_HOTELES.TIPOHABITACION TB
  WHERE TB.IDTIPOHABITACION IN (SELECT IDTIPOHABITACION
                                FROM TABLA_HOTELES.HABITACIONES H
                                WHERE H.IDHABITACION = vIDHABITACION);
END A_TX2_RETORNAR_COSTOH;